### ISSUE TITLE
HM1 zad 4. - pomoc w lokalizacji buga

### ISSUE THREAD

**Issue by Mcrackers** [daftcode/daftacademy-python_levelup-spring2020#12]
Szanowni,
Po obejrzeniu dzisiejszego rozwiązania zadania 4 z zaskoczeniem stwierdzam, że jest bardzo podobne do wypracowanego przeze mnie. Jednak w odróżnieniu od rozwiązania zaprezentowanego podczas wykładu, mój kod nie przechodzi testów.
Chciałbym prosić o pomoc w zlokalizowaniu buga. Poniżej zamieszczam kod main.py, a zaraz za nim test_main.py.

```
#main.py
from fastapi import FastAPI
from pydantic import BaseModel
from fastapi.responses import JSONResponse
app = FastAPI()
app.num = 0
app.count = -1
patlist = []


@app.get("/")
def root():
	return {"message": "Hello World during the coronavirus pandemic!"}


@app.get("/num")
def num():
	app.num += 1
	return app.num


@app.get("/patient")
def l_patients():
	return {"lista": patlist}


class Request(BaseModel):
	name: str
	surename: str


class Respond(BaseModel):
	id: int = None
	patient: dict


@app.post("/patient", response_model=Respond)
def new_patient(data: Request):
	if data:
		patlist.append(data.dict())
		app.count +=1
	return Respond(id = app.count, patient = data.dict())


@app.get("/patient/{pk}")
def get_patient(pk: int):
	if pk in range(len(patlist)):
		return Request(name = patlist[pk]["name"], surename = patlist[pk]["surename"])
	else:
		return JSONResponse(status_code=204, content={})

#test_main.py
import pytest
from fastapi.testclient import TestClient
from main import app

client = TestClient(app)


def test_read_main():
	response = client.get("/")
	assert response.status_code == 200
	assert response.json() == {"message": "Hello World during the coronavirus pandemic!"}


def test_get_patient():
	response = client.get(f"/patient/{0}")
	assert response.status_code == 204
	assert response.json() == {}


def test_add_patient1():
	response = client.post("/patient", json={"name": "janusz", "surename": "biznesu"})
	assert response.status_code == 200
	assert response.json() == {"id": 0, "patient": {"name": "janusz", "surename": "biznesu"}}
	response2 = client.post("/patient", json={"name": "śółć", "surename": "ąck"})
	assert response2.status_code == 200
	assert response2.json() == {"id": 1, "patient": {"name": "śółć", "surename": "ąck"}}


@pytest.mark.parametrize("data", [{"name": "janusz", "surename": "biznesu"}, {"name": "marek", "surename": "0"}, {"name": "krotka", "surename": "$tok_rotka!@#$"}])
def test_add_patient(data):
	response = client.post("/patient", json=data)
	assert response.status_code == 200
	assert response.json() == {"id": app.count, "patient": data}



def test_get_patient2():
	response = client.get(f"/patient/{0}")
	assert response.status_code == 200
	assert response.json() == {"name": "janusz", "surename": "biznesu"}
	response = client.get(f"/patient/{0}")
	assert response.status_code == 200
	assert response.json() == {"name": "janusz", "surename": "biznesu"}
	response2 = client.get(f"/patient/{300}")
	assert response2.status_code == 204
	assert response2.json() == {}
```

**Comment by mateusz94** [comment]
Proszę napisać których testów

**Comment by Mcrackers** [comment]
Problem dotyczy testów na repl.it:
-response_structure
-unexisted_patient

Za każdym razem otrzymuję zwrot w postaci:
```
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 18, in setUp
    self.my_results = [response.json() for response in self.responses]
  File "/home/runner/unit_tests.py", line 18, in <listcomp>
    self.my_results = [response.json() for response in self.responses]
  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.8/site-packages/requests/models.py", line 889, in json
    return complexjson.loads(
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 20, in setUp
    raise Exception("Your response are not JSON! {}".format(str(e)))
Exception: Your response are not JSON! Expecting value: line 1 column 1 (char 0)
```

**Comment by mateusz94** [comment]
Wykononująć POST na adres URL/patient nie otrzymuję poprawnej odpowiedzi. Czy Twoja aplikacja w ogóle działa?

**Comment by Mcrackers** [comment]
Wydaje mi się, że tak (ale dlatego tu jestem żeby się tego też nauczyć). Czy jest inny sposób na sprawdzenie tego od podanego poniżej?
Zapytanie o nieistniejącego pacjenta:
```
(venv) mariusz@karbenek:~/Dokumenty/NaukaProgramowania/DaftAcademy/Z1_HW1$ curl -X GET "https://mmhomework.herokuapp.com/patient/20" -H  "accept: application/json" -v
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 18.203.208.214...
* TCP_NODELAY set
* Connected to mmhomework.herokuapp.com (18.203.208.214) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Heroku, Inc.; CN=*.herokuapp.com
*  start date: Apr 19 00:00:00 2017 GMT
*  expire date: Jun 22 12:00:00 2020 GMT
*  subjectAltName: host "mmhomework.herokuapp.com" matched cert's "*.herokuapp.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
> GET /patient/20 HTTP/1.1
> Host: mmhomework.herokuapp.com
> User-Agent: curl/7.58.0
> accept: application/json
> 
< HTTP/1.1 204 No Content
< Connection: keep-alive
< Date: Tue, 07 Apr 2020 09:36:07 GMT
< Server: uvicorn
< Content-Length: 2
< Content-Type: application/json
< Via: 1.1 vegur
< 
* Connection #0 to host mmhomework.herokuapp.com left intact
```
Dodanie nowego pacjenta:
```
(venv) mariusz@karbenek:~/Dokumenty/NaukaProgramowania/DaftAcademy/Z1_HW1$ curl -X POST "https://mmhomework.herokuapp.com/patient" -H  "ion/json" -d "{\"name\":\"Henryk\",\"surename\":\"liść\"}" -v
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 54.171.40.67...
* TCP_NODELAY set
* Connected to mmhomework.herokuapp.com (54.171.40.67) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Heroku, Inc.; CN=*.herokuapp.com
*  start date: Apr 19 00:00:00 2017 GMT
*  expire date: Jun 22 12:00:00 2020 GMT
*  subjectAltName: host "mmhomework.herokuapp.com" matched cert's "*.herokuapp.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
> POST /patient HTTP/1.1
> Host: mmhomework.herokuapp.com
> User-Agent: curl/7.58.0
> accept: application/json
> Content-Type: application/json
> Content-Length: 37
> 
* upload completely sent off: 37 out of 37 bytes
< HTTP/1.1 200 OK
< Connection: keep-alive
< Date: Tue, 07 Apr 2020 09:39:46 GMT
< Server: uvicorn
< Content-Length: 56
< Content-Type: application/json
< Via: 1.1 vegur
< 
* Connection #0 to host mmhomework.herokuapp.com left intact
```
Zapytanie o pacjetna:
```
(venv) mariusz@karbenek:~/Dokumenty/NaukaProgramowania/DaftAcademy/Z1_HW1$ curl -X GET "https://mmhomework.herokuapp.com/patient/3" -H  "accept: application/json" -v
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 52.16.211.175...
* TCP_NODELAY set
* Connected to mmhomework.herokuapp.com (52.16.211.175) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Heroku, Inc.; CN=*.herokuapp.com
*  start date: Apr 19 00:00:00 2017 GMT
*  expire date: Jun 22 12:00:00 2020 GMT
*  subjectAltName: host "mmhomework.herokuapp.com" matched cert's "*.herokuapp.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
> GET /patient/3 HTTP/1.1
> Host: mmhomework.herokuapp.com
> User-Agent: curl/7.58.0
> accept: application/json
> 
< HTTP/1.1 200 OK
< Connection: keep-alive
< Date: Tue, 07 Apr 2020 09:42:59 GMT
< Server: uvicorn
< Content-Length: 37
< Content-Type: application/json
< Via: 1.1 vegur
< 
* Connection #0 to host mmhomework.herokuapp.com left intact
```

**Comment by mateusz94** [comment]
Jakiego podałeś URLa?

**Comment by mateusz94** [comment]
Testowałem ręcznie i wydaje się wszystko git

**Comment by mateusz94** [comment]
Możesz np tak testować:

```python
>>> import requests
>>> requests.post("https://mmhomework.herokuapp.com/patient", json={"name": "m", "surename": "l"})
<Response [200]>
>>> res = requests.post("https://mmhomework.herokuapp.com/patient", json={"name": "m", "surename": "l"})
>>> res.json()
{'id': 13, 'patient': {'name': 'm', 'surename': 'l'}}
```

**Comment by mateusz94** [comment]
Możesz też użyć konsoli heroku, żeby podejrzeć logi i na bieżąco monitorować odpowiedzi.

**Comment by Mcrackers** [comment]
Rzeczywiście, miałem literówkę w adresie url, który wkleiłem (sic!) do repl.it.
Przynajmniej wiem, że poprawię testuję i piszę, co dla mnie jest szalenie cenne.
Bardzo dziękuję za pomoc i udzielone rady!

Do zamknięcia.
